# Generated by Django 3.1.7 on 2021-03-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice', '0002_auto_20210316_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
